source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BUKPhotoBrowser_Example', :exclusive => true do
  pod "BUKPhotoBrowser", :path => "../"
end

target 'BUKPhotoBrowser_Tests', :exclusive => true do
  pod "BUKPhotoBrowser", :path => "../"

  
end
