source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '7.0'

target 'BUKPhotoBrowser_Example' do
  pod "BUKPhotoBrowser", :path => "../"

  target 'BUKPhotoBrowser_Tests' do
    inherit! :search_paths
  end
end

